apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-ui
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      containers:
      - name: frontend
        image: mywebregistry.azurecr.io/frontend:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---    
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 4200
    targetPort: 80
  selector:
    app: web-ui